### ISSUE TITLE
Need a simple gallery view section

### ISSUE THREAD

**Issue by blackhatbrigade** [blackhatbrigade/wedding#2]
This is actually pending the upload portion.

**Comment by dylan-wright** [comment]
Some design considerations from phone convo with @blackhatbrigade 

![ink 1](https://user-images.githubusercontent.com/16417223/27518191-171f87f4-5997-11e7-9c8c-6462622f63d5.png)

**Comment by blackhatbrigade** [comment]
That is a fantastic image....

**Comment by dylan-wright** [comment]
![1rhp9u](https://user-images.githubusercontent.com/16417223/27518285-775597c4-5999-11e7-820e-77a3382a6dc4.jpg)

**Comment by dylan-wright** [comment]
Basic functionality done. Still need to:
- style @HawpT 
- permissions
- a default/all gallery? what do you think @blackhatbrigade

**Comment by blackhatbrigade** [comment]
I'm not excited about the functionality you pushed.  You have to click "View" to upload the picture?  And you have to "Edit" to add the caption?  I think I was expecting them to be on the same form under edit?

And yeah, a "all" gallery should be just the default.  This site doesn't need any real organization right now.  Although being able to sort or search by a specific user would probably be useful.

**Comment by dylan-wright** [comment]
Yeah the way it is now is kinda dumb. That PR was more about the upload/retrieve photo part than the actual user story

**Comment by blackhatbrigade** [comment]
Why I approved it.  We can modify the UX portion as needed as long as the functionality exists.

**Comment by JasonSHD** [comment]
I did some tweaks.  Considering this issue finished
